hero_image: images/compose-tune.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Compose your own tune
description: Use code to make your first programmed piece of music
original_url: https://codeclubprojects.org/en-GB/sonic-pi/compose-tune
interests: music/sound
technologies: ''
site_areas: codeclub, sonic-pi
steps:
- title: Introduction
- title: Play your first notes
- title: 'Challenge: Improve the chime'
- title: Repeat the chime
- title: 'Challenge: Repeat 4 times'
- title: Recording your chime
- title: 'Challenge: Compose a new tune'

